CREATE TABLE [CONF].[COMPONENTE] (
    [CODIGO_COMPONENTE]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [CODIGO_SISTEMA]        BIGINT        NOT NULL,
    [TIPO_COMPONENTE]       VARCHAR (100) NOT NULL,
    [NOMBRE_COMPONENTE]     VARCHAR (100) NOT NULL,
    [DESCRIPCION]           VARCHAR (200) NULL,
    [ESTADO_REGISTRO]       CHAR (1)      NOT NULL,
    [USUARIO_CREACION]      VARCHAR (100) NOT NULL,
    [FECHA_CREACION]        DATETIME      NOT NULL,
    [TERMINAL_CREACION]     VARCHAR (100) NOT NULL,
    [USUARIO_MODIFICACION]  VARCHAR (100) NULL,
    [FECHA_MODIFICACION]    DATETIME      NULL,
    [TERMINAL_MODIFICACION] VARCHAR (100) NULL,
    CONSTRAINT [PK_COMPONENTE] PRIMARY KEY CLUSTERED ([CODIGO_COMPONENTE] ASC),
    CONSTRAINT [FK_COMPONENTE_SISTEMA] FOREIGN KEY ([CODIGO_SISTEMA]) REFERENCES [CONF].[SISTEMA] ([CODIGO_SISTEMA])
);

