CREATE TABLE [CONF].[COMPONENTE_VERSION] (
    [CODIGO_COMPONENTE_VERSION] BIGINT         IDENTITY (1, 1) NOT NULL,
    [CODIGO_SISTEMA_VERSION]    BIGINT         NOT NULL,
    [CODIGO_COMPONENTE]         BIGINT         NOT NULL,
    [CODIGO_REQUERIMIENTO]      VARCHAR (100)  NOT NULL,
    [NOMBRE_TAGS]               VARCHAR (100)  NOT NULL,
    [REPOSITORIO]               NVARCHAR (300) NULL,
    [CANTIDAD_ITERACIONES]      INT            NOT NULL,
    [ESTADO_REGISTRO]           CHAR (1)       NOT NULL,
    [USUARIO_CREACION]          VARCHAR (100)  NOT NULL,
    [FECHA_CREACION]            DATETIME       NOT NULL,
    [TERMINAL_CREACION]         VARCHAR (100)  NOT NULL,
    [USUARIO_MODIFICACION]      VARCHAR (100)  NULL,
    [FECHA_MODIFICACION]        DATETIME       NULL,
    [TERMINAL_MODIFICACION]     VARCHAR (100)  NULL,
    CONSTRAINT [PK_COMPONENTE_VERSION] PRIMARY KEY CLUSTERED ([CODIGO_COMPONENTE_VERSION] ASC),
    CONSTRAINT [FK_COMPONENTE_VERSION_COMPONENTE] FOREIGN KEY ([CODIGO_COMPONENTE]) REFERENCES [CONF].[COMPONENTE] ([CODIGO_COMPONENTE]),
    CONSTRAINT [FK_COMPONENTE_VERSION_SISTEMA_VERSION] FOREIGN KEY ([CODIGO_SISTEMA_VERSION]) REFERENCES [CONF].[SISTEMA_VERSION] ([CODIGO_SISTEMA_VERSION])
);

