CREATE TABLE [CONF].[SISTEMA_VERSION] (
    [CODIGO_SISTEMA_VERSION] BIGINT        IDENTITY (1, 1) NOT NULL,
    [CODIGO_SISTEMA]         BIGINT        NOT NULL,
    [CODIGO_PASE]            VARCHAR (100) NOT NULL,
    [NOMBRE_VERSION]         VARCHAR (100) NOT NULL,
    [ESTADO_REGISTRO]        CHAR (1)      NOT NULL,
    [USUARIO_CREACION]       VARCHAR (100) NOT NULL,
    [FECHA_CREACION]         DATETIME      NOT NULL,
    [TERMINAL_CREACION]      VARCHAR (100) NOT NULL,
    [USUARIO_MODIFICACION]   VARCHAR (100) NULL,
    [FECHA_MODIFICACION]     DATETIME      NULL,
    [TERMINAL_MODIFICACION]  VARCHAR (100) NULL,
    CONSTRAINT [PK_SISTEMA_VERSION] PRIMARY KEY CLUSTERED ([CODIGO_SISTEMA_VERSION] ASC),
    CONSTRAINT [FK_SISTEMA_VERSION_SISTEMA] FOREIGN KEY ([CODIGO_SISTEMA]) REFERENCES [CONF].[SISTEMA] ([CODIGO_SISTEMA])
);

