//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Shared.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta conforme con los datos a procesar?.
        /// </summary>
        public static string EtiquetaAceptarResumen {
            get {
                return ResourceManager.GetString("EtiquetaAceptarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string EtiquetaActualiacionExito {
            get {
                return ResourceManager.GetString("EtiquetaActualiacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización Realizada con Éxito.
        /// </summary>
        public static string EtiquetaActualizacionConforme {
            get {
                return ResourceManager.GetString("EtiquetaActualizacionConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes para la actualización.
        /// </summary>
        public static string EtiquetaActualizacionDatosIncompleto {
            get {
                return ResourceManager.GetString("EtiquetaActualizacionDatosIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha modificado ningún valor..
        /// </summary>
        public static string EtiquetaActualizacionDatosNoModificados {
            get {
                return ResourceManager.GetString("EtiquetaActualizacionDatosNoModificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente..
        /// </summary>
        public static string EtiquetaActualizacionError {
            get {
                return ResourceManager.GetString("EtiquetaActualizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string EtiquetaActualizar {
            get {
                return ResourceManager.GetString("EtiquetaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string EtiquetaAdvertencia {
            get {
                return ResourceManager.GetString("EtiquetaAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string EtiquetaAnadir {
            get {
                return ResourceManager.GetString("EtiquetaAnadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año(s).
        /// </summary>
        public static string EtiquetaAnio {
            get {
                return ResourceManager.GetString("EtiquetaAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular.
        /// </summary>
        public static string EtiquetaAnular {
            get {
                return ResourceManager.GetString("EtiquetaAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular Pago.
        /// </summary>
        public static string EtiquetaAnularPagoUtilizado {
            get {
                return ResourceManager.GetString("EtiquetaAnularPagoUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string EtiquetaAplicar {
            get {
                return ResourceManager.GetString("EtiquetaAplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Situación del Registro.
        /// </summary>
        public static string EtiquetaCabeceraSituacion {
            get {
                return ResourceManager.GetString("EtiquetaCabeceraSituacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación.
        /// </summary>
        public static string EtiquetaCabeceraValidacion {
            get {
                return ResourceManager.GetString("EtiquetaCabeceraValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Información.
        /// </summary>
        public static string EtiquetaCargarInformacion {
            get {
                return ResourceManager.GetString("EtiquetaCargarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string EtiquetaConfirmacion {
            get {
                return ResourceManager.GetString("EtiquetaConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea Guardar el Registro?.
        /// </summary>
        public static string EtiquetaConfirmacionGuardar {
            get {
                return ResourceManager.GetString("EtiquetaConfirmacionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string EtiquetaContinuar {
            get {
                return ResourceManager.GetString("EtiquetaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Desde Correcto.
        /// </summary>
        public static string EtiquetaCorrectoDesde {
            get {
                return ResourceManager.GetString("EtiquetaCorrectoDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Hasta Correcto.
        /// </summary>
        public static string EtiquetaCorrectoHasta {
            get {
                return ResourceManager.GetString("EtiquetaCorrectoHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterios de Búsqueda.
        /// </summary>
        public static string EtiquetaCriterioBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaCriterioBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string EtiquetaCriterioModificar {
            get {
                return ResourceManager.GetString("EtiquetaCriterioModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string EtiquetaCriterioNuevo {
            get {
                return ResourceManager.GetString("EtiquetaCriterioNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Pago.
        /// </summary>
        public static string EtiquetaDetallePagoUtilizado {
            get {
                return ResourceManager.GetString("EtiquetaDetallePagoUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día(s).
        /// </summary>
        public static string EtiquetaDia {
            get {
                return ResourceManager.GetString("EtiquetaDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento de Identidad.
        /// </summary>
        public static string EtiquetaDocumentoIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Registro.
        /// </summary>
        public static string EtiquetaEditarTooltip {
            get {
                return ResourceManager.GetString("EtiquetaEditarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija un color.
        /// </summary>
        public static string EtiquetaElijaColor {
            get {
                return ResourceManager.GetString("EtiquetaElijaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro eliminado correctamente..
        /// </summary>
        public static string EtiquetaEliminar {
            get {
                return ResourceManager.GetString("EtiquetaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo eliminar el registro. Ya está procesado..
        /// </summary>
        public static string EtiquetaErrorEliminar {
            get {
                return ResourceManager.GetString("EtiquetaErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente..
        /// </summary>
        public static string EtiquetaErrorRegistro {
            get {
                return ResourceManager.GetString("EtiquetaErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Notificación.
        /// </summary>
        public static string EtiquetaFechaNotificacion {
            get {
                return ResourceManager.GetString("EtiquetaFechaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Vencimiento.
        /// </summary>
        public static string EtiquetaFechaVencimiento {
            get {
                return ResourceManager.GetString("EtiquetaFechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        public static string EtiquetaFiltrar {
            get {
                return ResourceManager.GetString("EtiquetaFiltrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string EtiquetaFiltro {
            get {
                return ResourceManager.GetString("EtiquetaFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Archivo.
        /// </summary>
        public static string EtiquetaGenerarArchivo {
            get {
                return ResourceManager.GetString("EtiquetaGenerarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string EtiquetaGrabarExito {
            get {
                return ResourceManager.GetString("EtiquetaGrabarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string EtiquetaGrupo {
            get {
                return ResourceManager.GetString("EtiquetaGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string EtiquetaImprimir {
            get {
                return ResourceManager.GetString("EtiquetaImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string EtiquetaInformacion {
            get {
                return ResourceManager.GetString("EtiquetaInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos con (&lt;span class=&quot;danger&quot;&gt;*&lt;/span&gt;) son obligatorios..
        /// </summary>
        public static string EtiquetaInformativoCamposObligatorios {
            get {
                return ResourceManager.GetString("EtiquetaInformativoCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros para la búsqueda realizada..
        /// </summary>
        public static string EtiquetaInformativoNoSeEncontraronRegistros {
            get {
                return ResourceManager.GetString("EtiquetaInformativoNoSeEncontraronRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes(es).
        /// </summary>
        public static string EtiquetaMes {
            get {
                return ResourceManager.GetString("EtiquetaMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea suspender acción de cobranza?.
        /// </summary>
        public static string EtiquetaModificarRegistro {
            get {
                return ResourceManager.GetString("EtiquetaModificarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda.
        /// </summary>
        public static string EtiquetaMoneda {
            get {
                return ResourceManager.GetString("EtiquetaMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        public static string EtiquetaMotivo {
            get {
                return ResourceManager.GetString("EtiquetaMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        public static string EtiquetaNinguno {
            get {
                return ResourceManager.GetString("EtiquetaNinguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pre - Generar.
        /// </summary>
        public static string EtiquetaPreGenerar {
            get {
                return ResourceManager.GetString("EtiquetaPreGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar.
        /// </summary>
        public static string EtiquetaProcesar {
            get {
                return ResourceManager.GetString("EtiquetaProcesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string EtiquetaProveedor {
            get {
                return ResourceManager.GetString("EtiquetaProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor de Cobranza.
        /// </summary>
        public static string EtiquetaProveedorCobranza {
            get {
                return ResourceManager.GetString("EtiquetaProveedorCobranza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de Fechas Correcto.
        /// </summary>
        public static string EtiquetaRangoFechas {
            get {
                return ResourceManager.GetString("EtiquetaRangoFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reasignar.
        /// </summary>
        public static string EtiquetaReasignar {
            get {
                return ResourceManager.GetString("EtiquetaReasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro realizado con éxito..
        /// </summary>
        public static string EtiquetaRegistroConforme {
            get {
                return ResourceManager.GetString("EtiquetaRegistroConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes para el registro.
        /// </summary>
        public static string EtiquetaRegistroDatosIncompleto {
            get {
                return ResourceManager.GetString("EtiquetaRegistroDatosIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ingresado ya se encuentra registrado..
        /// </summary>
        public static string EtiquetaRegistroDuplicado {
            get {
                return ResourceManager.GetString("EtiquetaRegistroDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string EtiquetaRegresar {
            get {
                return ResourceManager.GetString("EtiquetaRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de Búsqueda.
        /// </summary>
        public static string EtiquetaResultadoBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Registro.
        /// </summary>
        public static string EtiquetaSeleccionarTooltip {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendientes.
        /// </summary>
        public static string EtiquetaSeleccionPendientes {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        public static string EtiquetaSubirArchivo {
            get {
                return ResourceManager.GetString("EtiquetaSubirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Extensión Válido - extensión .txt.
        /// </summary>
        public static string EtiquetaTipoExtensionValido {
            get {
                return ResourceManager.GetString("EtiquetaTipoExtensionValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Moneda.
        /// </summary>
        public static string EtiquetaTipoMoneda {
            get {
                return ResourceManager.GetString("EtiquetaTipoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Proceso.
        /// </summary>
        public static string EtiquetaTipoProceso {
            get {
                return ResourceManager.GetString("EtiquetaTipoProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo Requerido.
        /// </summary>
        public static string EtiquetaTituloCampoRequerido {
            get {
                return ResourceManager.GetString("EtiquetaTituloCampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL.
        /// </summary>
        public static string EtiquetaTotal {
            get {
                return ResourceManager.GetString("EtiquetaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transparente.
        /// </summary>
        public static string EtiquetaTransparente {
            get {
                return ResourceManager.GetString("EtiquetaTransparente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Archivo.
        /// </summary>
        public static string EtiquetaVerArchivoTooltip {
            get {
                return ResourceManager.GetString("EtiquetaVerArchivoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Detalle.
        /// </summary>
        public static string EtiquetaVerDetalle {
            get {
                return ResourceManager.GetString("EtiquetaVerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string LabelAccept {
            get {
                return ResourceManager.GetString("LabelAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string LabelArea {
            get {
                return ResourceManager.GetString("LabelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string LabelClean {
            get {
                return ResourceManager.GetString("LabelClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string LabelClose {
            get {
                return ResourceManager.GetString("LabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;.
        /// </summary>
        public static string LabelConcatenateUrlMenu {
            get {
                return ResourceManager.GetString("LabelConcatenateUrlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string LabelConfirmationHeader {
            get {
                return ResourceManager.GetString("LabelConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular Registro.
        /// </summary>
        public static string LabelDeleteRecord {
            get {
                return ResourceManager.GetString("LabelDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Registro.
        /// </summary>
        public static string LabelDeleteTooltip {
            get {
                return ResourceManager.GetString("LabelDeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Registro.
        /// </summary>
        public static string LabelEditRecord {
            get {
                return ResourceManager.GetString("LabelEditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        public static string LabelExport {
            get {
                return ResourceManager.GetString("LabelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string LabelFrom {
            get {
                return ResourceManager.GetString("LabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        public static string LabelGenerate {
            get {
                return ResourceManager.GetString("LabelGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string LabelGetOut {
            get {
                return ResourceManager.GetString("LabelGetOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string LabelGridEdit {
            get {
                return ResourceManager.GetString("LabelGridEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        public static string LabelImport {
            get {
                return ResourceManager.GetString("LabelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando....
        /// </summary>
        public static string LabelLoading {
            get {
                return ResourceManager.GetString("LabelLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de Modificación.
        /// </summary>
        public static string LabelModificationReason {
            get {
                return ResourceManager.GetString("LabelModificationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar :.
        /// </summary>
        public static string LabelMustEnterField {
            get {
                return ResourceManager.GetString("LabelMustEnterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string LabelNext {
            get {
                return ResourceManager.GetString("LabelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        public static string LabelPage {
            get {
                return ResourceManager.GetString("LabelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Registro.
        /// </summary>
        public static string LabelRegistrationStatus {
            get {
                return ResourceManager.GetString("LabelRegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *** FIN DE {0} ***.
        /// </summary>
        public static string LabelReportEndOf {
            get {
                return ResourceManager.GetString("LabelReportEndOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos con (.
        /// </summary>
        public static string LabelRequiredField1 {
            get {
                return ResourceManager.GetString("LabelRequiredField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ) son obligatorios..
        /// </summary>
        public static string LabelRequiredField2 {
            get {
                return ResourceManager.GetString("LabelRequiredField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fila.
        /// </summary>
        public static string LabelRow {
            get {
                return ResourceManager.GetString("LabelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filas por Página.
        /// </summary>
        public static string LabelRowsPerPage {
            get {
                return ResourceManager.GetString("LabelRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string LabelSeacrh {
            get {
                return ResourceManager.GetString("LabelSeacrh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros para la búsqueda realizada..
        /// </summary>
        public static string LabelSearchResultsBlank {
            get {
                return ResourceManager.GetString("LabelSearchResultsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Logo.
        /// </summary>
        public static string LabelSeeCompanyLogo {
            get {
                return ResourceManager.GetString("LabelSeeCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Logo.
        /// </summary>
        public static string LabelSeeReportLogo {
            get {
                return ResourceManager.GetString("LabelSeeReportLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string LabelSelect {
            get {
                return ResourceManager.GetString("LabelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string LabelSelectAll {
            get {
                return ResourceManager.GetString("LabelSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar/Deseleccionar Todos.
        /// </summary>
        public static string LabelSelectDeselectAll {
            get {
                return ResourceManager.GetString("LabelSelectDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Filtro.
        /// </summary>
        public static string LabelSelectFilter {
            get {
                return ResourceManager.GetString("LabelSelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Registro.
        /// </summary>
        public static string LabelSelectRecord {
            get {
                return ResourceManager.GetString("LabelSelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string LabelShow {
            get {
                return ResourceManager.GetString("LabelShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un filtro de búsqueda..
        /// </summary>
        public static string LabelSomeInformationRequiredFields {
            get {
                return ResourceManager.GetString("LabelSomeInformationRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione una opción del sistema..
        /// </summary>
        public static string LabelSubTitleGreeting {
            get {
                return ResourceManager.GetString("LabelSubTitleGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE FLETES.
        /// </summary>
        public static string LabelSystem {
            get {
                return ResourceManager.GetString("LabelSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SFT.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al Sistema de Fletes (SFT).
        /// </summary>
        public static string LabelTitleHome {
            get {
                return ResourceManager.GetString("LabelTitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPORTE DE {0}.
        /// </summary>
        public static string LabelTitleReport {
            get {
                return ResourceManager.GetString("LabelTitleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string LabelTo {
            get {
                return ResourceManager.GetString("LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LabelUser {
            get {
                return ResourceManager.GetString("LabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Reporte.
        /// </summary>
        public static string LabelVisualize {
            get {
                return ResourceManager.GetString("LabelVisualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a formato inválido de la configuración de columnas.
        /// </summary>
        public static string ValidacionFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacionFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a valor del campo no es decimal:.
        /// </summary>
        public static string ValidacionNoDecimal {
            get {
                return ResourceManager.GetString("ValidacionNoDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe configuración para la entidad actual.
        /// </summary>
        public static string ValidacionNoExisteConfiguracion {
            get {
                return ResourceManager.GetString("ValidacionNoExisteConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a valor del campo no es fecha:.
        /// </summary>
        public static string ValidacionNoFecha {
            get {
                return ResourceManager.GetString("ValidacionNoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo generar el archivo:.
        /// </summary>
        public static string ValidacionNoGeneroArchivo {
            get {
                return ResourceManager.GetString("ValidacionNoGeneroArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a valor del campo no es número:.
        /// </summary>
        public static string ValidacionNoNumero {
            get {
                return ResourceManager.GetString("ValidacionNoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe información para la entidad recaudadora.
        /// </summary>
        public static string ValidacionSinInformacion {
            get {
                return ResourceManager.GetString("ValidacionSinInformacion", resourceCulture);
            }
        }
    }
}
