//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Freight.Simulator {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Freight.Simulator.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe de Flete.
        /// </summary>
        public static string LabelAmountFreight {
            get {
                return ResourceManager.GetString("LabelAmountFreight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campaña.
        /// </summary>
        public static string LabelCampaign {
            get {
                return ResourceManager.GetString("LabelCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Error.
        /// </summary>
        public static string LabelCodeError {
            get {
                return ResourceManager.GetString("LabelCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Parámetro 1.
        /// </summary>
        public static string LabelCodeParameter1 {
            get {
                return ResourceManager.GetString("LabelCodeParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Parámetro 2.
        /// </summary>
        public static string LabelCodeParameter2 {
            get {
                return ResourceManager.GetString("LabelCodeParameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Parámetro 3.
        /// </summary>
        public static string LabelCodeParameter3 {
            get {
                return ResourceManager.GetString("LabelCodeParameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combinación.
        /// </summary>
        public static string LabelCombination {
            get {
                return ResourceManager.GetString("LabelCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Pais.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Error.
        /// </summary>
        public static string LabelDescriptionError {
            get {
                return ResourceManager.GetString("LabelDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Envio.
        /// </summary>
        public static string LabelSendType {
            get {
                return ResourceManager.GetString("LabelSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simular.
        /// </summary>
        public static string LabelSimulate {
            get {
                return ResourceManager.GetString("LabelSimulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simulador.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Pedido.
        /// </summary>
        public static string LabelTypeOrder {
            get {
                return ResourceManager.GetString("LabelTypeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Parámetro 1.
        /// </summary>
        public static string LabelValueParameter1 {
            get {
                return ResourceManager.GetString("LabelValueParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Parámetro 2.
        /// </summary>
        public static string LabelValueParameter2 {
            get {
                return ResourceManager.GetString("LabelValueParameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Parámetro 3.
        /// </summary>
        public static string LabelValueParameter3 {
            get {
                return ResourceManager.GetString("LabelValueParameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semana.
        /// </summary>
        public static string LabelWeek {
            get {
                return ResourceManager.GetString("LabelWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año de Campaña.
        /// </summary>
        public static string LabelYearCampaign {
            get {
                return ResourceManager.GetString("LabelYearCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Zona.
        /// </summary>
        public static string LabelZone {
            get {
                return ResourceManager.GetString("LabelZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona de 11 caracteres.
        /// </summary>
        public static string LabelZoneLength {
            get {
                return ResourceManager.GetString("LabelZoneLength", resourceCulture);
            }
        }
    }
}
