//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Policy.BusinessUnitConfiguration {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Policy.BusinessUnitConfiguration.Ind" +
                            "exResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer Menú Principal.
        /// </summary>
        public static string LabelAcquiringMainMenu {
            get {
                return ResourceManager.GetString("LabelAcquiringMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Negocio.
        /// </summary>
        public static string LabelBusinessUnit {
            get {
                return ResourceManager.GetString("LabelBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Mínimo de Caracteres por Glosa debe ser mayor que 1 y menor que 100..
        /// </summary>
        public static string LabelCharacteresMinGloss {
            get {
                return ResourceManager.GetString("LabelCharacteresMinGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo de Caracteres por Glosa.
        /// </summary>
        public static string LabelCharactersMinimumGloss {
            get {
                return ResourceManager.GetString("LabelCharactersMinimumGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo de Compañía.
        /// </summary>
        public static string LabelCompanyLogo {
            get {
                return ResourceManager.GetString("LabelCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el Logo de la Compañia..
        /// </summary>
        public static string LabelCompanyLogoWithoutConfiguration {
            get {
                return ResourceManager.GetString("LabelCompanyLogoWithoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internacionalización.
        /// </summary>
        public static string LabelCulture {
            get {
                return ResourceManager.GetString("LabelCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Visualización de Reporte.
        /// </summary>
        public static string LabelDisplayFormReport {
            get {
                return ResourceManager.GetString("LabelDisplayFormReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Configuración ya existe para la Unidad de Negocio..
        /// </summary>
        public static string LabelExistingConfiguration {
            get {
                return ResourceManager.GetString("LabelExistingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer Menú Principal.
        /// </summary>
        public static string LabelGridAcquiringMainMenu {
            get {
                return ResourceManager.GetString("LabelGridAcquiringMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo de Caracteres por Glosa.
        /// </summary>
        public static string LabelGridCharactersMinimumGloss {
            get {
                return ResourceManager.GetString("LabelGridCharactersMinimumGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo de Compañia.
        /// </summary>
        public static string LabelGridCompanyLogo {
            get {
                return ResourceManager.GetString("LabelGridCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internacionalización.
        /// </summary>
        public static string LabelGridCulture {
            get {
                return ResourceManager.GetString("LabelGridCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Visualización de Reporte.
        /// </summary>
        public static string LabelGridDisplayFormReport {
            get {
                return ResourceManager.GetString("LabelGridDisplayFormReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo de Reporte.
        /// </summary>
        public static string LabelGridReportLogo {
            get {
                return ResourceManager.GetString("LabelGridReportLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filas por Página en Grillas.
        /// </summary>
        public static string LabelGridRowsPerPage {
            get {
                return ResourceManager.GetString("LabelGridRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona Horaria.
        /// </summary>
        public static string LabelGridTimeZone {
            get {
                return ResourceManager.GetString("LabelGridTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo de Vocales por Glosa.
        /// </summary>
        public static string LabelGridVowelsMinimumGloss {
            get {
                return ResourceManager.GetString("LabelGridVowelsMinimumGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un número menor o igual a 255 en Filas por Página en Grillas..
        /// </summary>
        public static string LabelMaxRowsPerPage {
            get {
                return ResourceManager.GetString("LabelMaxRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un número mayor a 0 en Filas por Página en Grillas..
        /// </summary>
        public static string LabelMinRowsPerPage {
            get {
                return ResourceManager.GetString("LabelMinRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo de Reporte.
        /// </summary>
        public static string LabelReportLogo {
            get {
                return ResourceManager.GetString("LabelReportLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el Logo de los Reportes..
        /// </summary>
        public static string LabelReportLogoWithoutConfiguration {
            get {
                return ResourceManager.GetString("LabelReportLogoWithoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filas por Página en Grillas.
        /// </summary>
        public static string LabelRowsPerPage {
            get {
                return ResourceManager.GetString("LabelRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona Horaria.
        /// </summary>
        public static string LabelTimeZone {
            get {
                return ResourceManager.GetString("LabelTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string LabelTitleBusinessUnitConfiguration {
            get {
                return ResourceManager.GetString("LabelTitleBusinessUnitConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Configuración.
        /// </summary>
        public static string LabelTitleEdit {
            get {
                return ResourceManager.GetString("LabelTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Configuración.
        /// </summary>
        public static string LabelTitleNew {
            get {
                return ResourceManager.GetString("LabelTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Mínimo de Vocales por Glosa debe ser mayor que 1 y menor que 100..
        /// </summary>
        public static string LabelVowelsMinGloss {
            get {
                return ResourceManager.GetString("LabelVowelsMinGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo de Vocales por Glosa.
        /// </summary>
        public static string LabelVowelsMinimumGloss {
            get {
                return ResourceManager.GetString("LabelVowelsMinimumGloss", resourceCulture);
            }
        }
    }
}
