//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Freight.Formula {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Freight.Formula.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Parámetro y Valor del Parámetro seleccionados ya existe en una Fórmula..
        /// </summary>
        public static string LabelExistingFormula {
            get {
                return ResourceManager.GetString("LabelExistingFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor.
        /// </summary>
        public static string LabelFactor {
            get {
                return ResourceManager.GetString("LabelFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Factor no puede ser 0.
        /// </summary>
        public static string LabelFactorMin {
            get {
                return ResourceManager.GetString("LabelFactorMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Factor.
        /// </summary>
        public static string LabelFactorType {
            get {
                return ResourceManager.GetString("LabelFactorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string LabelFactorTypeAmount {
            get {
                return ResourceManager.GetString("LabelFactorTypeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Fijo.
        /// </summary>
        public static string LabelFactorTypeFixedValue {
            get {
                return ResourceManager.GetString("LabelFactorTypeFixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        public static string LabelFactorTypePercentage {
            get {
                return ResourceManager.GetString("LabelFactorTypePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelGridCode {
            get {
                return ResourceManager.GetString("LabelGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor.
        /// </summary>
        public static string LabelGridFactor {
            get {
                return ResourceManager.GetString("LabelGridFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Factor.
        /// </summary>
        public static string LabelGridFactorType {
            get {
                return ResourceManager.GetString("LabelGridFactorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string LabelGridFactorTypeAmount {
            get {
                return ResourceManager.GetString("LabelGridFactorTypeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor fijo.
        /// </summary>
        public static string LabelGridFactorTypeFixedValue {
            get {
                return ResourceManager.GetString("LabelGridFactorTypeFixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        public static string LabelGridFactorTypePercentage {
            get {
                return ResourceManager.GetString("LabelGridFactorTypePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string LabelGridOperation {
            get {
                return ResourceManager.GetString("LabelGridOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string LabelGridParameter {
            get {
                return ResourceManager.GetString("LabelGridParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor del Parámetro.
        /// </summary>
        public static string LabelGridParameterValue {
            get {
                return ResourceManager.GetString("LabelGridParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de envío.
        /// </summary>
        public static string LabelGridSendType {
            get {
                return ResourceManager.GetString("LabelGridSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular la Fórmula porque está siendo utilizado en la opción de Prioridad de Fórmulas.
        /// </summary>
        public static string LabelInvalidCancellationFormula {
            get {
                return ResourceManager.GetString("LabelInvalidCancellationFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor mayor a 0 cuando la Operación es +, - ó /.
        /// </summary>
        public static string LabelInvalidFactorOperation {
            get {
                return ResourceManager.GetString("LabelInvalidFactorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string LabelOperation {
            get {
                return ResourceManager.GetString("LabelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +.
        /// </summary>
        public static string LabelOperationAddition {
            get {
                return ResourceManager.GetString("LabelOperationAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /.
        /// </summary>
        public static string LabelOperationDivision {
            get {
                return ResourceManager.GetString("LabelOperationDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        public static string LabelOperationMultiplication {
            get {
                return ResourceManager.GetString("LabelOperationMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        public static string LabelOperationSubtraction {
            get {
                return ResourceManager.GetString("LabelOperationSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string LabelParameter {
            get {
                return ResourceManager.GetString("LabelParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor del Parámetro.
        /// </summary>
        public static string LabelParameterValue {
            get {
                return ResourceManager.GetString("LabelParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Envio.
        /// </summary>
        public static string LabelSendType {
            get {
                return ResourceManager.GetString("LabelSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Fórmula.
        /// </summary>
        public static string LabelTitleEdit {
            get {
                return ResourceManager.GetString("LabelTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fórmulas.
        /// </summary>
        public static string LabelTitleFormula {
            get {
                return ResourceManager.GetString("LabelTitleFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Fórmula.
        /// </summary>
        public static string LabelTitleNew {
            get {
                return ResourceManager.GetString("LabelTitleNew", resourceCulture);
            }
        }
    }
}
