CREATE FUNCTION [MNT].[F_OBTENER_COMBINACION] (
	@CODIGO_COMBINACION		INT,
	@CODIGO_UNIDAD_NEGOCIO	INT
)
RETURNS NVARCHAR(3000)
AS 
BEGIN
DECLARE @COMBINACION NVARCHAR(3000)
SET @COMBINACION = ''

SELECT @COMBINACION = 
						@COMBINACION + ' ' + P.CODIGO + ': ' + 
						(CASE P.TIPO_PARAMETRO 
							WHEN 'TP1' THEN CP.VALOR 
							WHEN 'TP2' THEN (SELECT TOP 1 PV.VALOR FROM MNT.F_PARAMETRO_VALOR_LISTA_SECCION(@CODIGO_UNIDAD_NEGOCIO,P.CODIGO,'1',2) PV 
											WHERE PV.CODIGO = CP.VALOR)
							
							END) + 
						' -'
FROM MNT.COMBINACION_PARAMETRO CP
INNER JOIN MNT.PARAMETRO P ON CP.CODIGO_PARAMETRO = P.CODIGO_PARAMETRO AND P.ESTADO_REGISTRO = '1'
WHERE CP.ORDEN_COMBINACION > 0 AND CP.ESTADO_REGISTRO = '1' AND CP.CODIGO_COMBINACION = @CODIGO_COMBINACION
ORDER BY CP.CODIGO_COMBINACION ASC


RETURN SUBSTRING(@COMBINACION,0,LEN(@COMBINACION))
END


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Función que retorna la combinación.', @level0type = N'SCHEMA', @level0name = N'MNT', @level1type = N'FUNCTION', @level1name = N'F_OBTENER_COMBINACION';

