//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.FreightManagement.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.FreightManagement.Common.Messages.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Directora no existe.
        /// </summary>
        public static string CodigoDirectoraInexistente {
            get {
                return ResourceManager.GetString("CodigoDirectoraInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de anular el pago?.
        /// </summary>
        public static string ConfirmacionAnulacion {
            get {
                return ResourceManager.GetString("ConfirmacionAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string ConfirmacionEliminacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de identificar los registros?.
        /// </summary>
        public static string ConfirmacionIdentificar {
            get {
                return ResourceManager.GetString("ConfirmacionIdentificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de realizar el proceso de devolución?.
        /// </summary>
        public static string ConfirmacionProcesarSaldo {
            get {
                return ResourceManager.GetString("ConfirmacionProcesarSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Anulado Correctamente.
        /// </summary>
        public static string ConvenioPorDeudaAnuladoSatisfactorio {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaAnuladoSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Directora ya tiene Convenio(s).
        /// </summary>
        public static string ConvenioPorDeudaExisteConvenio {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaExisteConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convenio no puede ser Anulado, solo se pueden anular los convenios activos.
        /// </summary>
        public static string ConvenioPorDeudaValidarAnulacion {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe asociar deudas al Convenio.
        /// </summary>
        public static string ConvenioPorDeudaValidarAsociarDeuda {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarAsociarDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Calcular el Cronograma.
        /// </summary>
        public static string ConvenioPorDeudaValidarCalcularCuota {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarCalcularCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Cuotas distinta al cronograma.
        /// </summary>
        public static string ConvenioPorDeudaValidarCuotaDistinta {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarCuotaDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe monto de convenio.
        /// </summary>
        public static string ConvenioPorDeudaValidarCuotasMontoConvenio {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarCuotasMontoConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese número de cuotas.
        /// </summary>
        public static string ConvenioPorDeudaValidarCuotasNumeroCuotas {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarCuotasNumeroCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convenio Pagado ó Anulado.
        /// </summary>
        public static string ConvenioPorDeudaValidarEstadoConvenio {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarEstadoConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deuda a Convenir es mayor al Totalizado de Cuotas.
        /// </summary>
        public static string ConvenioPorDeudaValidarMontoConvenioMayor {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarMontoConvenioMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deuda a Convenir es menor al Totalizado de Cuotas.
        /// </summary>
        public static string ConvenioPorDeudaValidarMontoConvenioMenor {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarMontoConvenioMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deuda(s) asociada(s) a un Convenio:.
        /// </summary>
        public static string ConvenioPorDeudaValidarRegistro {
            get {
                return ResourceManager.GetString("ConvenioPorDeudaValidarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea anular el convenio ?.
        /// </summary>
        public static string ConvenioPorDeudConfirmarAnularConvenio {
            get {
                return ResourceManager.GetString("ConvenioPorDeudConfirmarAnularConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar comentario.
        /// </summary>
        public static string DebeIngresarComentario {
            get {
                return ResourceManager.GetString("DebeIngresarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar número de operación.
        /// </summary>
        public static string DebeIngresarNumeroOperacion {
            get {
                return ResourceManager.GetString("DebeIngresarNumeroOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar deudas que pertenezcan a la misma Consultora.
        /// </summary>
        public static string DebeSeleccionarDeudaMismaConsultora {
            get {
                return ResourceManager.GetString("DebeSeleccionarDeudaMismaConsultora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una Directora.
        /// </summary>
        public static string DebeSeleccionarDirectora {
            get {
                return ResourceManager.GetString("DebeSeleccionarDirectora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar entidad recaudadora.
        /// </summary>
        public static string DebeSeleccionarEntidadRecaudadora {
            get {
                return ResourceManager.GetString("DebeSeleccionarEntidadRecaudadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una cuenta.
        /// </summary>
        public static string DebeSeleccionarEntidadRecaudadoraCta {
            get {
                return ResourceManager.GetString("DebeSeleccionarEntidadRecaudadoraCta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una fecha.
        /// </summary>
        public static string DebeSeleccionarFecha {
            get {
                return ResourceManager.GetString("DebeSeleccionarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar motivo de cambio.
        /// </summary>
        public static string DebeSeleccionarMotivoCambio {
            get {
                return ResourceManager.GetString("DebeSeleccionarMotivoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un registro.
        /// </summary>
        public static string DebeSeleccionarRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar registros del mismo Producto Crédito para esta opción.
        /// </summary>
        public static string DebeSeleccionarRegistroMismoProducto {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistroMismoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar solo 1 registro.
        /// </summary>
        public static string DebeSeleccionarUnRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad Recaudadora distinto.
        /// </summary>
        public static string EntidadRecaudadoraDistinta {
            get {
                return ResourceManager.GetString("EntidadRecaudadoraDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consultora beneficiaria no puede ser la misma que la que asume..
        /// </summary>
        public static string ErrorConsultoraAsume {
            get {
                return ResourceManager.GetString("ErrorConsultoraAsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consultora que asume no puede ser la misma que la beneficiaria..
        /// </summary>
        public static string ErrorConsultoraBeneficiaria {
            get {
                return ResourceManager.GetString("ErrorConsultoraBeneficiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Consultora no existe.
        /// </summary>
        public static string ErrorConsultoraNoExiste {
            get {
                return ResourceManager.GetString("ErrorConsultoraNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consultora seleccionada no pertenece al grupo personal de la consultora que asume..
        /// </summary>
        public static string ErrorConsultoraNoGrupoPersonal {
            get {
                return ResourceManager.GetString("ErrorConsultoraNoGrupoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha ingresado la consultora..
        /// </summary>
        public static string ErrorConsultoraRepetida {
            get {
                return ResourceManager.GetString("ErrorConsultoraRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deudas para el proceso.
        /// </summary>
        public static string ErrorIngreseDeudas {
            get {
                return ResourceManager.GetString("ErrorIngreseDeudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione deudas para el proceso..
        /// </summary>
        public static string ErrorSeleccionDeudas {
            get {
                return ResourceManager.GetString("ErrorSeleccionDeudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una consultora para asumir la deuda..
        /// </summary>
        public static string ErrorSeleccioneConsultoraAsume {
            get {
                return ResourceManager.GetString("ErrorSeleccioneConsultoraAsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione pagos para el proceso..
        /// </summary>
        public static string ErrorSeleccionPagos {
            get {
                return ResourceManager.GetString("ErrorSeleccionPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : No es un valor decimal..
        /// </summary>
        public static string ExcelCampoNoDecimal {
            get {
                return ResourceManager.GetString("ExcelCampoNoDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : No se encontro referencia del campo en el archivo..
        /// </summary>
        public static string ExcelCampoNoEncontrado {
            get {
                return ResourceManager.GetString("ExcelCampoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : No es un valor de fecha correcto. Formato .
        /// </summary>
        public static string ExcelCampoNoFecha {
            get {
                return ResourceManager.GetString("ExcelCampoNoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : No es un valor numérico..
        /// </summary>
        public static string ExcelCampoNoNumerico {
            get {
                return ResourceManager.GetString("ExcelCampoNoNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de cobrador asociado no existe en la base de datos..
        /// </summary>
        public static string ExcelCodigoCobradorNoExiste {
            get {
                return ResourceManager.GetString("ExcelCodigoCobradorNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de deuda no está asignado al cobrador..
        /// </summary>
        public static string ExcelDeudaNoAsignadaCobrador {
            get {
                return ResourceManager.GetString("ExcelDeudaNoAsignadaCobrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe la acción judicial para realizar la confirmación..
        /// </summary>
        public static string ExcelNoExisteAccionJudicialConfirmar {
            get {
                return ResourceManager.GetString("ExcelNoExisteAccionJudicialConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de demanda asociado no existe en la base de datos..
        /// </summary>
        public static string ExcelNumeroDemandaNoExiste {
            get {
                return ResourceManager.GetString("ExcelNumeroDemandaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de deuda asociado no existe en la base de datos..
        /// </summary>
        public static string ExcelNumeroDeudaNoExiste {
            get {
                return ResourceManager.GetString("ExcelNumeroDeudaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se encuentra duplicado..
        /// </summary>
        public static string ExcelRegistroDuplicado {
            get {
                return ResourceManager.GetString("ExcelRegistroDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ya se encuentra en la base de datos.
        /// </summary>
        public static string ExcelRegistroDuplicadoBaseDatos {
            get {
                return ResourceManager.GetString("ExcelRegistroDuplicadoBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} : No tiene un tipo de dato configurado en politicas..
        /// </summary>
        public static string ExcelTipoCampoNoConsiderado {
            get {
                return ResourceManager.GetString("ExcelTipoCampoNoConsiderado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un documento registrado.
        /// </summary>
        public static string ExisteDocumentoRegistrado {
            get {
                return ResourceManager.GetString("ExisteDocumentoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al grabar el registro.
        /// </summary>
        public static string FailedSaved {
            get {
                return ResourceManager.GetString("FailedSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de depósito distinto.
        /// </summary>
        public static string FechaRegistroDistinta {
            get {
                return ResourceManager.GetString("FechaRegistroDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe de pago distinto.
        /// </summary>
        public static string ImportePagoDistinta {
            get {
                return ResourceManager.GetString("ImportePagoDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede seleccionar una consultora.
        /// </summary>
        public static string InformacionFiltroConsultora {
            get {
                return ResourceManager.GetString("InformacionFiltroConsultora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un filtro de búsqueda.
        /// </summary>
        public static string InformacionIngresarFiltro {
            get {
                return ResourceManager.GetString("InformacionIngresarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información mostrada corresponde a la.
        /// </summary>
        public static string InformacionPreFiltro {
            get {
                return ResourceManager.GetString("InformacionPreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito.
        /// </summary>
        public static string InformationSaved {
            get {
                return ResourceManager.GetString("InformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de Modificación Valido.
        /// </summary>
        public static string LabelValidationObservation {
            get {
                return ResourceManager.GetString("LabelValidationObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View model no definido.
        /// </summary>
        public static string LoadErrorViewModel {
            get {
                return ResourceManager.GetString("LoadErrorViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no tiene Acceso..
        /// </summary>
        public static string MessageErrorLogOn {
            get {
                return ResourceManager.GetString("MessageErrorLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o Contraseña Incorrecto.
        /// </summary>
        public static string MessageErrorPassOn {
            get {
                return ResourceManager.GetString("MessageErrorPassOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El importe reportado no coincide con el importe reportado por la entidad recaudadora.
        /// </summary>
        public static string MontoPagoNoCoincide {
            get {
                return ResourceManager.GetString("MontoPagoNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede Registrar Pago Duplicado.
        /// </summary>
        public static string NoRegistrarPagoDuplicado {
            get {
                return ResourceManager.GetString("NoRegistrarPagoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de cuenta distinto.
        /// </summary>
        public static string NumeroCuentaDistinta {
            get {
                return ResourceManager.GetString("NumeroCuentaDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de operacion distinto.
        /// </summary>
        public static string NumeroOperacionDistinta {
            get {
                return ResourceManager.GetString("NumeroOperacionDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de referencia distinto.
        /// </summary>
        public static string NumeroReferenciaDistinta {
            get {
                return ResourceManager.GetString("NumeroReferenciaDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago identificado correctamente.
        /// </summary>
        public static string PagoIdentificadoCorrectamente {
            get {
                return ResourceManager.GetString("PagoIdentificadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago identificado correctamente.
        /// </summary>
        public static string PagoIdentificadoCorrecto {
            get {
                return ResourceManager.GetString("PagoIdentificadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los registros seleccionados no coinciden:.
        /// </summary>
        public static string RegistrosNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrosNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta opción solo está habilitada si el estado del crédito es Aprobado..
        /// </summary>
        public static string RestriccionEstadoCredito {
            get {
                return ResourceManager.GetString("RestriccionEstadoCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string SatisfactorySaved {
            get {
                return ResourceManager.GetString("SatisfactorySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de grabar los cambios solicitados?.
        /// </summary>
        public static string SaveConfirmation {
            get {
                return ResourceManager.GetString("SaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se anuló registro con éxito.
        /// </summary>
        public static string SeAnuloRegistro {
            get {
                return ResourceManager.GetString("SeAnuloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para esta opción debe seleccionar una directora..
        /// </summary>
        public static string SeleccioneConsultora {
            get {
                return ResourceManager.GetString("SeleccioneConsultora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos un parámetro de filtro correcto..
        /// </summary>
        public static string SeleccioneFiltro {
            get {
                return ResourceManager.GetString("SeleccioneFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de cuotas supera al número de campañas restantes..
        /// </summary>
        public static string ValidaMaximoCuotas {
            get {
                return ResourceManager.GetString("ValidaMaximoCuotas", resourceCulture);
            }
        }
    }
}
