//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Policy.TaxProfile {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Policy.TaxProfile.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Perfil Tributario de Directora.
        /// </summary>
        public static string labelAddTaxProfileDirector {
            get {
                return ResourceManager.GetString("labelAddTaxProfileDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autónoma.
        /// </summary>
        public static string labelAutonomus {
            get {
                return ResourceManager.GetString("labelAutonomus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelCode {
            get {
                return ResourceManager.GetString("labelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Directora.
        /// </summary>
        public static string LabelCodeDirector {
            get {
                return ResourceManager.GetString("LabelCodeDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un código válido..
        /// </summary>
        public static string LabelCodeValid {
            get {
                return ResourceManager.GetString("LabelCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima Declaración.
        /// </summary>
        public static string labelDeclarationLast {
            get {
                return ResourceManager.GetString("labelDeclarationLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ultima Declaración:.
        /// </summary>
        public static string labelDeclarationLastDate {
            get {
                return ResourceManager.GetString("labelDeclarationLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exoneraciones.
        /// </summary>
        public static string labelExeptions {
            get {
                return ResourceManager.GetString("labelExeptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autónoma.
        /// </summary>
        public static string LabelGridAutonumus {
            get {
                return ResourceManager.GetString("LabelGridAutonumus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelGridCode {
            get {
                return ResourceManager.GetString("labelGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima Declaración.
        /// </summary>
        public static string LabelGridDeclarationLast {
            get {
                return ResourceManager.GetString("LabelGridDeclarationLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exoneración.
        /// </summary>
        public static string labelGridExeptions {
            get {
                return ResourceManager.GetString("labelGridExeptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelGridName {
            get {
                return ResourceManager.GetString("labelGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Persona.
        /// </summary>
        public static string LabelGridPersonType {
            get {
                return ResourceManager.GetString("LabelGridPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del Registro.
        /// </summary>
        public static string LabelGridStatusRegister {
            get {
                return ResourceManager.GetString("LabelGridStatusRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regimen Tributario.
        /// </summary>
        public static string LabelGridTaxRegimen {
            get {
                return ResourceManager.GetString("LabelGridTaxRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Directora.
        /// </summary>
        public static string labelNameDirector {
            get {
                return ResourceManager.GetString("labelNameDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre..
        /// </summary>
        public static string LabelParameterNameValid {
            get {
                return ResourceManager.GetString("LabelParameterNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Persona.
        /// </summary>
        public static string LabelPersonType {
            get {
                return ResourceManager.GetString("LabelPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Tributario.
        /// </summary>
        public static string LabelRegisterTax {
            get {
                return ResourceManager.GetString("LabelRegisterTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Registro.
        /// </summary>
        public static string LabelStatusRegister {
            get {
                return ResourceManager.GetString("LabelStatusRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regimen Tributario.
        /// </summary>
        public static string labelTaxRegimen {
            get {
                return ResourceManager.GetString("labelTaxRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil Tributario Directora.
        /// </summary>
        public static string labelTittleTaxProfile {
            get {
                return ResourceManager.GetString("labelTittleTaxProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el/los valor(es).
        /// </summary>
        public static string labelValueValidate {
            get {
                return ResourceManager.GetString("labelValueValidate", resourceCulture);
            }
        }
    }
}
