//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Freight.Combination {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Freight.Combination.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string ColumnAmount {
            get {
                return ResourceManager.GetString("ColumnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string ColumnCode {
            get {
                return ResourceManager.GetString("ColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combinación.
        /// </summary>
        public static string ColumnCombination {
            get {
                return ResourceManager.GetString("ColumnCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Registro.
        /// </summary>
        public static string ColumnRegistrationStatus {
            get {
                return ResourceManager.GetString("ColumnRegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combinación ya registrada..
        /// </summary>
        public static string LabelExistingCombination {
            get {
                return ResourceManager.GetString("LabelExistingCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La combinación ingresada ya existe..
        /// </summary>
        public static string LabelExistingParameter {
            get {
                return ResourceManager.GetString("LabelExistingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un Importe mayor a 0.
        /// </summary>
        public static string LabelFreightAmountMin {
            get {
                return ResourceManager.GetString("LabelFreightAmountMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string LabelGridAmount {
            get {
                return ResourceManager.GetString("LabelGridAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelGridCode {
            get {
                return ResourceManager.GetString("LabelGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combinación.
        /// </summary>
        public static string LabelGridCombination {
            get {
                return ResourceManager.GetString("LabelGridCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LabelGridDescription {
            get {
                return ResourceManager.GetString("LabelGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que añadir al menos un Parámetro para la Combinación.
        /// </summary>
        public static string LabelGridNull {
            get {
                return ResourceManager.GetString("LabelGridNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string LabelGridParameter {
            get {
                return ResourceManager.GetString("LabelGridParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros.
        /// </summary>
        public static string LabelGridParameters {
            get {
                return ResourceManager.GetString("LabelGridParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string LabelGridValue {
            get {
                return ResourceManager.GetString("LabelGridValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        public static string LabelHour {
            get {
                return ResourceManager.GetString("LabelHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Parámetros de la Combinación no son Validos.
        /// </summary>
        public static string LabelInvalidParameter {
            get {
                return ResourceManager.GetString("LabelInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        public static string LabelPage {
            get {
                return ResourceManager.GetString("LabelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string LabelPageOf {
            get {
                return ResourceManager.GetString("LabelPageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string LabelParameter {
            get {
                return ResourceManager.GetString("LabelParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los Parámetros para la Combinación fueron añadidos.
        /// </summary>
        public static string LabelParameterCombinationDisable {
            get {
                return ResourceManager.GetString("LabelParameterCombinationDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Valor del Parámetro Tipo Rango se Cruza con otro Valor del mismo tipo en otra Combinación.
        /// </summary>
        public static string LabelParameterInvalidRange {
            get {
                return ResourceManager.GetString("LabelParameterInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor del Parámetro.
        /// </summary>
        public static string LabelParameterValue {
            get {
                return ResourceManager.GetString("LabelParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Registro.
        /// </summary>
        public static string LabelRegistrationStatus {
            get {
                return ResourceManager.GetString("LabelRegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la Combinación.
        /// </summary>
        public static string LabelSubTitleDataCombination {
            get {
                return ResourceManager.GetString("LabelSubTitleDataCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros de la Combinación.
        /// </summary>
        public static string LabelSubTitleParameterCombination {
            get {
                return ResourceManager.GetString("LabelSubTitleParameterCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combinación.
        /// </summary>
        public static string LabelTitleCombination {
            get {
                return ResourceManager.GetString("LabelTitleCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Combinación.
        /// </summary>
        public static string LabelTitleCombinationReport {
            get {
                return ResourceManager.GetString("LabelTitleCombinationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Combinación.
        /// </summary>
        public static string LabelTitleEdit {
            get {
                return ResourceManager.GetString("LabelTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Combinación.
        /// </summary>
        public static string LabelTitleNew {
            get {
                return ResourceManager.GetString("LabelTitleNew", resourceCulture);
            }
        }
    }
}
