//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Proxies.Application.SRAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:gmd:contract:task:security", ConfigurationName="SRAService.ISRAService")]
    public interface ISRAService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación getRoles no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:getRoles", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.SRAService.getRolesResponse getRoles(Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:getRoles", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.getRolesResponse> getRolesAsync(Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación searchCountryUser no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:searchCountryUser", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserResponse searchCountryUser(Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:searchCountryUser", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserResponse> searchCountryUserAsync(Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación loginAdministrator no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:loginAdministrator", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorResponse loginAdministrator(Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:loginAdministrator", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorResponse> loginAdministratorAsync(Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación login no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:login", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.SRAService.loginResponse login(Yanbal.SFT.Proxies.Application.SRAService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:login", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.loginResponse> loginAsync(Yanbal.SFT.Proxies.Application.SRAService.loginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación permissionAccess no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:permissionAccess", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.SRAService.permissionAccessResponse permissionAccess(Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:gmd:contract:task:security:permissionAccess", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.permissionAccessResponse> permissionAccessAsync(Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class GetRolesRequestType : GenericTypeRequest {
        
        private RolesRequest getRolesRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RolesRequest GetRolesRequest {
            get {
                return this.getRolesRequestField;
            }
            set {
                this.getRolesRequestField = value;
                this.RaisePropertyChanged("GetRolesRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class RolesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemCodeField;
        
        private string roleCodeField;
        
        private string roleNameField;
        
        private string userCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string roleCode {
            get {
                return this.roleCodeField;
            }
            set {
                this.roleCodeField = value;
                this.RaisePropertyChanged("roleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("roleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string userCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
                this.RaisePropertyChanged("userCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class Permission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int systemCodeField;
        
        private string systemIdentificationCodeField;
        
        private string systemNameField;
        
        private string systemDescriptionField;
        
        private string systemPathField;
        
        private int moduleCodeField;
        
        private string moduleIdentificationCodeField;
        
        private string moduleNameField;
        
        private string moduleDescriptionField;
        
        private string moduleIconClassNameField;
        
        private bool externalURLFlagField;
        
        private string moduleURLField;
        
        private int optionCodeField;
        
        private string optionIdentificationCodeField;
        
        private string optionNameField;
        
        private string optionDescriptionField;
        
        private string optionURLField;
        
        private int actionCodeField;
        
        private string actionIdentificationCodeField;
        
        private string actionNameField;
        
        private string actionDescriptionField;
        
        private string statusField;
        
        private string parentResultIdField;
        
        private string resultTypeField;
        
        private int referenceResultIdField;
        
        private string resultIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string systemIdentificationCode {
            get {
                return this.systemIdentificationCodeField;
            }
            set {
                this.systemIdentificationCodeField = value;
                this.RaisePropertyChanged("systemIdentificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string systemName {
            get {
                return this.systemNameField;
            }
            set {
                this.systemNameField = value;
                this.RaisePropertyChanged("systemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string systemDescription {
            get {
                return this.systemDescriptionField;
            }
            set {
                this.systemDescriptionField = value;
                this.RaisePropertyChanged("systemDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string systemPath {
            get {
                return this.systemPathField;
            }
            set {
                this.systemPathField = value;
                this.RaisePropertyChanged("systemPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int moduleCode {
            get {
                return this.moduleCodeField;
            }
            set {
                this.moduleCodeField = value;
                this.RaisePropertyChanged("moduleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string moduleIdentificationCode {
            get {
                return this.moduleIdentificationCodeField;
            }
            set {
                this.moduleIdentificationCodeField = value;
                this.RaisePropertyChanged("moduleIdentificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string moduleName {
            get {
                return this.moduleNameField;
            }
            set {
                this.moduleNameField = value;
                this.RaisePropertyChanged("moduleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string moduleDescription {
            get {
                return this.moduleDescriptionField;
            }
            set {
                this.moduleDescriptionField = value;
                this.RaisePropertyChanged("moduleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string moduleIconClassName {
            get {
                return this.moduleIconClassNameField;
            }
            set {
                this.moduleIconClassNameField = value;
                this.RaisePropertyChanged("moduleIconClassName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool externalURLFlag {
            get {
                return this.externalURLFlagField;
            }
            set {
                this.externalURLFlagField = value;
                this.RaisePropertyChanged("externalURLFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string moduleURL {
            get {
                return this.moduleURLField;
            }
            set {
                this.moduleURLField = value;
                this.RaisePropertyChanged("moduleURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int optionCode {
            get {
                return this.optionCodeField;
            }
            set {
                this.optionCodeField = value;
                this.RaisePropertyChanged("optionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string optionIdentificationCode {
            get {
                return this.optionIdentificationCodeField;
            }
            set {
                this.optionIdentificationCodeField = value;
                this.RaisePropertyChanged("optionIdentificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string optionName {
            get {
                return this.optionNameField;
            }
            set {
                this.optionNameField = value;
                this.RaisePropertyChanged("optionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string optionDescription {
            get {
                return this.optionDescriptionField;
            }
            set {
                this.optionDescriptionField = value;
                this.RaisePropertyChanged("optionDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string optionURL {
            get {
                return this.optionURLField;
            }
            set {
                this.optionURLField = value;
                this.RaisePropertyChanged("optionURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("actionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string actionIdentificationCode {
            get {
                return this.actionIdentificationCodeField;
            }
            set {
                this.actionIdentificationCodeField = value;
                this.RaisePropertyChanged("actionIdentificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string actionName {
            get {
                return this.actionNameField;
            }
            set {
                this.actionNameField = value;
                this.RaisePropertyChanged("actionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string actionDescription {
            get {
                return this.actionDescriptionField;
            }
            set {
                this.actionDescriptionField = value;
                this.RaisePropertyChanged("actionDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string parentResultId {
            get {
                return this.parentResultIdField;
            }
            set {
                this.parentResultIdField = value;
                this.RaisePropertyChanged("parentResultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string resultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
                this.RaisePropertyChanged("resultType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int referenceResultId {
            get {
                return this.referenceResultIdField;
            }
            set {
                this.referenceResultIdField = value;
                this.RaisePropertyChanged("referenceResultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string resultId {
            get {
                return this.resultIdField;
            }
            set {
                this.resultIdField = value;
                this.RaisePropertyChanged("resultId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class PermissionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Permission[] listPermissionField;
        
        private bool cultureFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listPermission", Order=0)]
        public Permission[] listPermission {
            get {
                return this.listPermissionField;
            }
            set {
                this.listPermissionField = value;
                this.RaisePropertyChanged("listPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool cultureFlag {
            get {
                return this.cultureFlagField;
            }
            set {
                this.cultureFlagField = value;
                this.RaisePropertyChanged("cultureFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class LoginTypeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string countryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string countryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
                this.RaisePropertyChanged("countryName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class CountryUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Country[] listCountryField;
        
        private bool indicatorCorporateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listCountry", Order=0)]
        public Country[] listCountry {
            get {
                return this.listCountryField;
            }
            set {
                this.listCountryField = value;
                this.RaisePropertyChanged("listCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool indicatorCorporate {
            get {
                return this.indicatorCorporateField;
            }
            set {
                this.indicatorCorporateField = value;
                this.RaisePropertyChanged("indicatorCorporate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class RoleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string roleCodeField;
        
        private string roleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string roleCode {
            get {
                return this.roleCodeField;
            }
            set {
                this.roleCodeField = value;
                this.RaisePropertyChanged("roleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("roleName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:base")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private int severityField;
        
        private string dateRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DateRequest {
            get {
                return this.dateRequestField;
            }
            set {
                this.dateRequestField = value;
                this.RaisePropertyChanged("DateRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionAccessResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchCountryUserResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRolesResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:base")]
    public abstract partial class GenericTypeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseDateField;
        
        private ErrorType errorField;
        
        private Cabecera headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseDate {
            get {
                return this.responseDateField;
            }
            set {
                this.responseDateField = value;
                this.RaisePropertyChanged("responseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public Cabecera Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:base")]
    public partial class Cabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoInterfazField;
        
        private string usuarioAplicacionField;
        
        private string codigoAplicacionField;
        
        private string codigoPaisField;
        
        private CodigoPaisOD[] codigosPaisODField;
        
        private string idTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigoInterfaz {
            get {
                return this.codigoInterfazField;
            }
            set {
                this.codigoInterfazField = value;
                this.RaisePropertyChanged("codigoInterfaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string codigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
                this.RaisePropertyChanged("codigoAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string codigoPais {
            get {
                return this.codigoPaisField;
            }
            set {
                this.codigoPaisField = value;
                this.RaisePropertyChanged("codigoPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        public CodigoPaisOD[] codigosPaisOD {
            get {
                return this.codigosPaisODField;
            }
            set {
                this.codigosPaisODField = value;
                this.RaisePropertyChanged("codigosPaisOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:base")]
    public partial class CodigoPaisOD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class PermissionAccessResponseType : GenericTypeResponse {
        
        private PermissionResponse permissionAccessResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PermissionResponse PermissionAccessResponse {
            get {
                return this.permissionAccessResponseField;
            }
            set {
                this.permissionAccessResponseField = value;
                this.RaisePropertyChanged("PermissionAccessResponse");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class LoginResponseType : GenericTypeResponse {
        
        private LoginTypeResponse loginResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoginTypeResponse LoginResponse {
            get {
                return this.loginResponseField;
            }
            set {
                this.loginResponseField = value;
                this.RaisePropertyChanged("LoginResponse");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class SearchCountryUserResponseType : GenericTypeResponse {
        
        private CountryUserResponse searchCountryUserResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CountryUserResponse SearchCountryUserResponse {
            get {
                return this.searchCountryUserResponseField;
            }
            set {
                this.searchCountryUserResponseField = value;
                this.RaisePropertyChanged("SearchCountryUserResponse");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class GetRolesResponseType : GenericTypeResponse {
        
        private RoleType[] getRolesResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("roleType", Namespace="urn:gmd:schema:security", IsNullable=false)]
        public RoleType[] GetRolesResponse {
            get {
                return this.getRolesResponseField;
            }
            set {
                this.getRolesResponseField = value;
                this.RaisePropertyChanged("GetRolesResponse");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class PermissionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string systemIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string systemIdentificationCode {
            get {
                return this.systemIdentificationCodeField;
            }
            set {
                this.systemIdentificationCodeField = value;
                this.RaisePropertyChanged("systemIdentificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class LoginTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string passwordField;
        
        private string languageCodeField;
        
        private string systemCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("languageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:security")]
    public partial class CountryUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeSystemField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codeSystem {
            get {
                return this.codeSystemField;
            }
            set {
                this.codeSystemField = value;
                this.RaisePropertyChanged("codeSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionAccessRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchCountryUserRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRolesRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:schema:base")]
    public abstract partial class GenericTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestRunTimeField;
        
        private Cabecera headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestRunTime {
            get {
                return this.requestRunTimeField;
            }
            set {
                this.requestRunTimeField = value;
                this.RaisePropertyChanged("RequestRunTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Cabecera Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class PermissionAccessRequestType : GenericTypeRequest {
        
        private PermissionRequest permissionAccessRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PermissionRequest PermissionAccessRequest {
            get {
                return this.permissionAccessRequestField;
            }
            set {
                this.permissionAccessRequestField = value;
                this.RaisePropertyChanged("PermissionAccessRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class LoginRequestType : GenericTypeRequest {
        
        private LoginTypeRequest loginRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoginTypeRequest LoginRequest {
            get {
                return this.loginRequestField;
            }
            set {
                this.loginRequestField = value;
                this.RaisePropertyChanged("LoginRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmd:contract:task:security")]
    public partial class SearchCountryUserRequestType : GenericTypeRequest {
        
        private CountryUserRequest searchCountryUserRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CountryUserRequest SearchCountryUserRequest {
            get {
                return this.searchCountryUserRequestField;
            }
            set {
                this.searchCountryUserRequestField = value;
                this.RaisePropertyChanged("SearchCountryUserRequest");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRolesRequest", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.GetRolesRequestType getRolesRequest1;
        
        public getRolesRequest() {
        }
        
        public getRolesRequest(Yanbal.SFT.Proxies.Application.SRAService.GetRolesRequestType getRolesRequest1) {
            this.getRolesRequest1 = getRolesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRolesResponse", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.GetRolesResponseType getRolesResponse1;
        
        public getRolesResponse() {
        }
        
        public getRolesResponse(Yanbal.SFT.Proxies.Application.SRAService.GetRolesResponseType getRolesResponse1) {
            this.getRolesResponse1 = getRolesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCountryUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchCountryUserRequest", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserRequestType searchCountryUserRequest1;
        
        public searchCountryUserRequest() {
        }
        
        public searchCountryUserRequest(Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserRequestType searchCountryUserRequest1) {
            this.searchCountryUserRequest1 = searchCountryUserRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCountryUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchCountryUserResponse", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserResponseType searchCountryUserResponse1;
        
        public searchCountryUserResponse() {
        }
        
        public searchCountryUserResponse(Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserResponseType searchCountryUserResponse1) {
            this.searchCountryUserResponse1 = searchCountryUserResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginAdministratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginAdministratorRequest", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginAdministratorRequest1;
        
        public loginAdministratorRequest() {
        }
        
        public loginAdministratorRequest(Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginAdministratorRequest1) {
            this.loginAdministratorRequest1 = loginAdministratorRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginAdministratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginAdministratorResponse", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.LoginResponseType loginAdministratorResponse1;
        
        public loginAdministratorResponse() {
        }
        
        public loginAdministratorResponse(Yanbal.SFT.Proxies.Application.SRAService.LoginResponseType loginAdministratorResponse1) {
            this.loginAdministratorResponse1 = loginAdministratorResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginRequest", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginRequest1;
        
        public loginRequest() {
        }
        
        public loginRequest(Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginRequest1) {
            this.loginRequest1 = loginRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.LoginResponseType loginResponse1;
        
        public loginResponse() {
        }
        
        public loginResponse(Yanbal.SFT.Proxies.Application.SRAService.LoginResponseType loginResponse1) {
            this.loginResponse1 = loginResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class permissionAccessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="permissionAccessRequest", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessRequestType permissionAccessRequest1;
        
        public permissionAccessRequest() {
        }
        
        public permissionAccessRequest(Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessRequestType permissionAccessRequest1) {
            this.permissionAccessRequest1 = permissionAccessRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class permissionAccessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="permissionAccessResponse", Namespace="urn:gmd:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessResponseType permissionAccessResponse1;
        
        public permissionAccessResponse() {
        }
        
        public permissionAccessResponse(Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessResponseType permissionAccessResponse1) {
            this.permissionAccessResponse1 = permissionAccessResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISRAServiceChannel : Yanbal.SFT.Proxies.Application.SRAService.ISRAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRAServiceClient : System.ServiceModel.ClientBase<Yanbal.SFT.Proxies.Application.SRAService.ISRAService>, Yanbal.SFT.Proxies.Application.SRAService.ISRAService {
        
        public SRAServiceClient() {
        }
        
        public SRAServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRAServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRAServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.SRAService.getRolesResponse Yanbal.SFT.Proxies.Application.SRAService.ISRAService.getRoles(Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest request) {
            return base.Channel.getRoles(request);
        }
        
        public Yanbal.SFT.Proxies.Application.SRAService.GetRolesResponseType getRoles(Yanbal.SFT.Proxies.Application.SRAService.GetRolesRequestType getRolesRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest();
            inValue.getRolesRequest1 = getRolesRequest1;
            Yanbal.SFT.Proxies.Application.SRAService.getRolesResponse retVal = ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).getRoles(inValue);
            return retVal.getRolesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.getRolesResponse> Yanbal.SFT.Proxies.Application.SRAService.ISRAService.getRolesAsync(Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest request) {
            return base.Channel.getRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.getRolesResponse> getRolesAsync(Yanbal.SFT.Proxies.Application.SRAService.GetRolesRequestType getRolesRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.getRolesRequest();
            inValue.getRolesRequest1 = getRolesRequest1;
            return ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).getRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserResponse Yanbal.SFT.Proxies.Application.SRAService.ISRAService.searchCountryUser(Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest request) {
            return base.Channel.searchCountryUser(request);
        }
        
        public Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserResponseType searchCountryUser(Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserRequestType searchCountryUserRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest();
            inValue.searchCountryUserRequest1 = searchCountryUserRequest1;
            Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserResponse retVal = ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).searchCountryUser(inValue);
            return retVal.searchCountryUserResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserResponse> Yanbal.SFT.Proxies.Application.SRAService.ISRAService.searchCountryUserAsync(Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest request) {
            return base.Channel.searchCountryUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserResponse> searchCountryUserAsync(Yanbal.SFT.Proxies.Application.SRAService.SearchCountryUserRequestType searchCountryUserRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.searchCountryUserRequest();
            inValue.searchCountryUserRequest1 = searchCountryUserRequest1;
            return ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).searchCountryUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorResponse Yanbal.SFT.Proxies.Application.SRAService.ISRAService.loginAdministrator(Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest request) {
            return base.Channel.loginAdministrator(request);
        }
        
        public Yanbal.SFT.Proxies.Application.SRAService.LoginResponseType loginAdministrator(Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginAdministratorRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest();
            inValue.loginAdministratorRequest1 = loginAdministratorRequest1;
            Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorResponse retVal = ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).loginAdministrator(inValue);
            return retVal.loginAdministratorResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorResponse> Yanbal.SFT.Proxies.Application.SRAService.ISRAService.loginAdministratorAsync(Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest request) {
            return base.Channel.loginAdministratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorResponse> loginAdministratorAsync(Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginAdministratorRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.loginAdministratorRequest();
            inValue.loginAdministratorRequest1 = loginAdministratorRequest1;
            return ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).loginAdministratorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.SRAService.loginResponse Yanbal.SFT.Proxies.Application.SRAService.ISRAService.login(Yanbal.SFT.Proxies.Application.SRAService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public Yanbal.SFT.Proxies.Application.SRAService.LoginResponseType login(Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.loginRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.loginRequest();
            inValue.loginRequest1 = loginRequest1;
            Yanbal.SFT.Proxies.Application.SRAService.loginResponse retVal = ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).login(inValue);
            return retVal.loginResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.loginResponse> Yanbal.SFT.Proxies.Application.SRAService.ISRAService.loginAsync(Yanbal.SFT.Proxies.Application.SRAService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.loginResponse> loginAsync(Yanbal.SFT.Proxies.Application.SRAService.LoginRequestType loginRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.loginRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.loginRequest();
            inValue.loginRequest1 = loginRequest1;
            return ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.SRAService.permissionAccessResponse Yanbal.SFT.Proxies.Application.SRAService.ISRAService.permissionAccess(Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest request) {
            return base.Channel.permissionAccess(request);
        }
        
        public Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessResponseType permissionAccess(Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessRequestType permissionAccessRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest();
            inValue.permissionAccessRequest1 = permissionAccessRequest1;
            Yanbal.SFT.Proxies.Application.SRAService.permissionAccessResponse retVal = ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).permissionAccess(inValue);
            return retVal.permissionAccessResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.permissionAccessResponse> Yanbal.SFT.Proxies.Application.SRAService.ISRAService.permissionAccessAsync(Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest request) {
            return base.Channel.permissionAccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.SRAService.permissionAccessResponse> permissionAccessAsync(Yanbal.SFT.Proxies.Application.SRAService.PermissionAccessRequestType permissionAccessRequest1) {
            Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest inValue = new Yanbal.SFT.Proxies.Application.SRAService.permissionAccessRequest();
            inValue.permissionAccessRequest1 = permissionAccessRequest1;
            return ((Yanbal.SFT.Proxies.Application.SRAService.ISRAService)(this)).permissionAccessAsync(inValue);
        }
    }
}
