	
CREATE PROCEDURE [CONF].[USP_REGISTRO_CAMBIOS_INS](
	@NUMERO VARCHAR(255),
	@TAG VARCHAR(255),
	@HASHKEY VARCHAR(255),
	@SISTEMA VARCHAR(255),
	@RETROCESO VARCHAR(255),
	@USUARIO_CREACION VARCHAR(50),
	@TERMINAL_CREACION VARCHAR(50)
) AS 
BEGIN
	INSERT INTO CONF.REGISTRO_CAMBIOS(
		NUMERO,
		TAG,
		HASHKEY,
		SISTEMA,
		RETROCESO,
		USUARIO_CREACION,
		FECHA_CREACION,
		TERMINAL_CREACION	
	)
	VALUES(
		@NUMERO,
		@TAG,
		@HASHKEY,
		@SISTEMA,
		@RETROCESO,
		@USUARIO_CREACION,
		GETDATE(),
		@TERMINAL_CREACION	
	)
END
