//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Policy.ParameterValue {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Policy.ParameterValue.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string LabelBtnSearchParameter {
            get {
                return ResourceManager.GetString("LabelBtnSearchParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Parámetro.
        /// </summary>
        public static string LabelCodeParameter {
            get {
                return ResourceManager.GetString("LabelCodeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un código válido..
        /// </summary>
        public static string LabelCodeParameterValid {
            get {
                return ResourceManager.GetString("LabelCodeParameterValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Sección.
        /// </summary>
        public static string LabelCodeSection {
            get {
                return ResourceManager.GetString("LabelCodeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string LabelCodeValue {
            get {
                return ResourceManager.GetString("LabelCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Valor de Parámetro con el mismo Código. .
        /// </summary>
        public static string LabelDuplicateParameter {
            get {
                return ResourceManager.GetString("LabelDuplicateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen secciones para este parámetro..
        /// </summary>
        public static string LabelNoSections {
            get {
                return ResourceManager.GetString("LabelNoSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string LabelParameter {
            get {
                return ResourceManager.GetString("LabelParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre..
        /// </summary>
        public static string LabelParameterNameValid {
            get {
                return ResourceManager.GetString("LabelParameterNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un parámetro desde el botón Buscar..
        /// </summary>
        public static string LabelParameterValid {
            get {
                return ResourceManager.GetString("LabelParameterValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular el Valor de Parámetro o modificar el Código, porque está siendo usado en la opción de Fórmulas..
        /// </summary>
        public static string LabelParameterValueExistingInTableFormula {
            get {
                return ResourceManager.GetString("LabelParameterValueExistingInTableFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular el Valor de Parámetro, modificar el Código ó modificar los valores de Inicio - Fin (Parámetros de Tipo Valor Rango), porque está siendo usado en la opción de Combinaciones..
        /// </summary>
        public static string LabelParameterValueExistingInTableParameterCombination {
            get {
                return ResourceManager.GetString("LabelParameterValueExistingInTableParameterCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular el Valor de Parámetro o modificar el Código, porque está siendo usado en la opción de Combinaciones y en la opción de Fórmulas..
        /// </summary>
        public static string LabelParameterValueExistingInTableParameterCombinationFormula {
            get {
                return ResourceManager.GetString("LabelParameterValueExistingInTableParameterCombinationFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de Fin del Rango no puede ser menor al valor de Inicio.
        /// </summary>
        public static string LabelRangeDataInvalid {
            get {
                return ResourceManager.GetString("LabelRangeDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección.
        /// </summary>
        public static string LabelSection {
            get {
                return ResourceManager.GetString("LabelSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Valor.
        /// </summary>
        public static string LabelTitleEdit {
            get {
                return ResourceManager.GetString("LabelTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Valor.
        /// </summary>
        public static string LabelTitleNew {
            get {
                return ResourceManager.GetString("LabelTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de Parámetro General.
        /// </summary>
        public static string LabelTittleParameterValue {
            get {
                return ResourceManager.GetString("LabelTittleParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un Parámetro.
        /// </summary>
        public static string LabelValidateParameter {
            get {
                return ResourceManager.GetString("LabelValidateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string LabelValue {
            get {
                return ResourceManager.GetString("LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el/los valor(es).
        /// </summary>
        public static string LabelValueValidate {
            get {
                return ResourceManager.GetString("LabelValueValidate", resourceCulture);
            }
        }
    }
}
