//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Proxies.Application.TokenSecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:pyf:contract:task:security", ConfigurationName="TokenSecurityService.ITokenSecurityService")]
    public interface ITokenSecurityService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación generateTokenSecurity no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:pyf:contract:task:security:generateTokenSecurity", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityResponse generateTokenSecurity(Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pyf:contract:task:security:generateTokenSecurity", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityResponse> generateTokenSecurityAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación getTokenSecurityByTokenId no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:pyf:contract:task:security:getTokenSecurityByTokenId", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdResponse getTokenSecurityByTokenId(Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pyf:contract:task:security:getTokenSecurityByTokenId", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdResponse> getTokenSecurityByTokenIdAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación setExpireTokenSecurityById no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:pyf:contract:task:security:setExpireTokenSecurityById", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GenericTypeRequest))]
        Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdResponse setExpireTokenSecurityById(Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pyf:contract:task:security:setExpireTokenSecurityById", ReplyAction="")]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdResponse> setExpireTokenSecurityByIdAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:contract:task:security")]
    public partial class TokenSecurityGeneratedRequestType : GenericTypeRequest {
        
        private TokenSecurityGeneratedType tokenSecurityGeneratedRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:pyf:schema:token", Order=0)]
        public TokenSecurityGeneratedType TokenSecurityGeneratedRequest {
            get {
                return this.tokenSecurityGeneratedRequestField;
            }
            set {
                this.tokenSecurityGeneratedRequestField = value;
                this.RaisePropertyChanged("TokenSecurityGeneratedRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:token")]
    public partial class TokenSecurityGeneratedType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string userFirstNameField;
        
        private string roleCodeField;
        
        private string languageCodeField;
        
        private string businessUnitCodeField;
        
        private string systemCodeField;
        
        private string roleNameField;
        
        private string cultureCodeField;
        
        private string currentConsultantCodeField;
        
        private System.Nullable<System.DateTime> expirationTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
                this.RaisePropertyChanged("userFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string roleCode {
            get {
                return this.roleCodeField;
            }
            set {
                this.roleCodeField = value;
                this.RaisePropertyChanged("roleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("languageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string businessUnitCode {
            get {
                return this.businessUnitCodeField;
            }
            set {
                this.businessUnitCodeField = value;
                this.RaisePropertyChanged("businessUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("roleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cultureCode {
            get {
                return this.cultureCodeField;
            }
            set {
                this.cultureCodeField = value;
                this.RaisePropertyChanged("cultureCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string currentConsultantCode {
            get {
                return this.currentConsultantCodeField;
            }
            set {
                this.currentConsultantCodeField = value;
                this.RaisePropertyChanged("currentConsultantCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> expirationTime {
            get {
                return this.expirationTimeField;
            }
            set {
                this.expirationTimeField = value;
                this.RaisePropertyChanged("expirationTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:token")]
    public partial class TokenSecurity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenSecurityIdField;
        
        private System.DateTime expirationTimeField;
        
        private string userNameField;
        
        private string userFirstNameField;
        
        private string roleCodeField;
        
        private string languageCodeField;
        
        private string businessUnitCodeField;
        
        private string systemCodeField;
        
        private string roleNameField;
        
        private string cultureCodeField;
        
        private string currentConsultantCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tokenSecurityId {
            get {
                return this.tokenSecurityIdField;
            }
            set {
                this.tokenSecurityIdField = value;
                this.RaisePropertyChanged("tokenSecurityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime expirationTime {
            get {
                return this.expirationTimeField;
            }
            set {
                this.expirationTimeField = value;
                this.RaisePropertyChanged("expirationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string userFirstName {
            get {
                return this.userFirstNameField;
            }
            set {
                this.userFirstNameField = value;
                this.RaisePropertyChanged("userFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string roleCode {
            get {
                return this.roleCodeField;
            }
            set {
                this.roleCodeField = value;
                this.RaisePropertyChanged("roleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("languageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string businessUnitCode {
            get {
                return this.businessUnitCodeField;
            }
            set {
                this.businessUnitCodeField = value;
                this.RaisePropertyChanged("businessUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
                this.RaisePropertyChanged("systemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("roleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string cultureCode {
            get {
                return this.cultureCodeField;
            }
            set {
                this.cultureCodeField = value;
                this.RaisePropertyChanged("cultureCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string currentConsultantCode {
            get {
                return this.currentConsultantCodeField;
            }
            set {
                this.currentConsultantCodeField = value;
                this.RaisePropertyChanged("currentConsultantCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:base")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        private int severityField;
        
        private string dateRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DateRequest {
            get {
                return this.dateRequestField;
            }
            set {
                this.dateRequestField = value;
                this.RaisePropertyChanged("DateRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TokenSecurityInformationResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TokenSecurityGeneratedResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:base")]
    public abstract partial class GenericTypeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseDateField;
        
        private ErrorType errorField;
        
        private Cabecera headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseDate {
            get {
                return this.responseDateField;
            }
            set {
                this.responseDateField = value;
                this.RaisePropertyChanged("responseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public Cabecera Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:base")]
    public partial class Cabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoInterfazField;
        
        private string usuarioAplicacionField;
        
        private string codigoAplicacionField;
        
        private string codigoPaisField;
        
        private CodigoPaisOD[] codigosPaisODField;
        
        private string idTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigoInterfaz {
            get {
                return this.codigoInterfazField;
            }
            set {
                this.codigoInterfazField = value;
                this.RaisePropertyChanged("codigoInterfaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string codigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
                this.RaisePropertyChanged("codigoAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string codigoPais {
            get {
                return this.codigoPaisField;
            }
            set {
                this.codigoPaisField = value;
                this.RaisePropertyChanged("codigoPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        public CodigoPaisOD[] codigosPaisOD {
            get {
                return this.codigosPaisODField;
            }
            set {
                this.codigosPaisODField = value;
                this.RaisePropertyChanged("codigosPaisOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:base")]
    public partial class CodigoPaisOD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:contract:task:security")]
    public partial class TokenSecurityInformationResponseType : GenericTypeResponse {
        
        private TokenSecurity tokenSecurityInformationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:pyf:schema:token", Order=0)]
        public TokenSecurity TokenSecurityInformationResponse {
            get {
                return this.tokenSecurityInformationResponseField;
            }
            set {
                this.tokenSecurityInformationResponseField = value;
                this.RaisePropertyChanged("TokenSecurityInformationResponse");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:contract:task:security")]
    public partial class TokenSecurityGeneratedResponseType : GenericTypeResponse {
        
        private TokenSecurity tokenSecurityGeneratedResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:pyf:schema:token", Order=0)]
        public TokenSecurity TokenSecurityGeneratedResponse {
            get {
                return this.tokenSecurityGeneratedResponseField;
            }
            set {
                this.tokenSecurityGeneratedResponseField = value;
                this.RaisePropertyChanged("TokenSecurityGeneratedResponse");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:token")]
    public partial class TokenSecurityInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenSecurityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tokenSecurityId {
            get {
                return this.tokenSecurityIdField;
            }
            set {
                this.tokenSecurityIdField = value;
                this.RaisePropertyChanged("tokenSecurityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TokenSecurityInformationRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TokenSecurityGeneratedRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:schema:base")]
    public abstract partial class GenericTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestRunTimeField;
        
        private Cabecera headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestRunTime {
            get {
                return this.requestRunTimeField;
            }
            set {
                this.requestRunTimeField = value;
                this.RaisePropertyChanged("RequestRunTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Cabecera Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pyf:contract:task:security")]
    public partial class TokenSecurityInformationRequestType : GenericTypeRequest {
        
        private TokenSecurityInformationType tokenSecurityInformationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:pyf:schema:token", Order=0)]
        public TokenSecurityInformationType TokenSecurityInformationRequest {
            get {
                return this.tokenSecurityInformationRequestField;
            }
            set {
                this.tokenSecurityInformationRequestField = value;
                this.RaisePropertyChanged("TokenSecurityInformationRequest");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateTokenSecurityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pyf:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedRequestType TokenSecurityRequest;
        
        public generateTokenSecurityRequest() {
        }
        
        public generateTokenSecurityRequest(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedRequestType TokenSecurityRequest) {
            this.TokenSecurityRequest = TokenSecurityRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateTokenSecurityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pyf:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedResponseType TokenSecurityResponse;
        
        public generateTokenSecurityResponse() {
        }
        
        public generateTokenSecurityResponse(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedResponseType TokenSecurityResponse) {
            this.TokenSecurityResponse = TokenSecurityResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTokenSecurityByTokenIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pyf:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest;
        
        public getTokenSecurityByTokenIdRequest() {
        }
        
        public getTokenSecurityByTokenIdRequest(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest) {
            this.TokenSecurityInformationRequest = TokenSecurityInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTokenSecurityByTokenIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pyf:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationResponseType TokenSecurityInformationResponse;
        
        public getTokenSecurityByTokenIdResponse() {
        }
        
        public getTokenSecurityByTokenIdResponse(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationResponseType TokenSecurityInformationResponse) {
            this.TokenSecurityInformationResponse = TokenSecurityInformationResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setExpireTokenSecurityByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pyf:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest;
        
        public setExpireTokenSecurityByIdRequest() {
        }
        
        public setExpireTokenSecurityByIdRequest(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest) {
            this.TokenSecurityInformationRequest = TokenSecurityInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setExpireTokenSecurityByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pyf:contract:task:security", Order=0)]
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationResponseType TokenSecurityInformationResponse;
        
        public setExpireTokenSecurityByIdResponse() {
        }
        
        public setExpireTokenSecurityByIdResponse(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationResponseType TokenSecurityInformationResponse) {
            this.TokenSecurityInformationResponse = TokenSecurityInformationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenSecurityServiceChannel : Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenSecurityServiceClient : System.ServiceModel.ClientBase<Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService>, Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService {
        
        public TokenSecurityServiceClient() {
        }
        
        public TokenSecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenSecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenSecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenSecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityResponse Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService.generateTokenSecurity(Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest request) {
            return base.Channel.generateTokenSecurity(request);
        }
        
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedResponseType generateTokenSecurity(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedRequestType TokenSecurityRequest) {
            Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest inValue = new Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest();
            inValue.TokenSecurityRequest = TokenSecurityRequest;
            Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityResponse retVal = ((Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService)(this)).generateTokenSecurity(inValue);
            return retVal.TokenSecurityResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityResponse> Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService.generateTokenSecurityAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest request) {
            return base.Channel.generateTokenSecurityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityResponse> generateTokenSecurityAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityGeneratedRequestType TokenSecurityRequest) {
            Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest inValue = new Yanbal.SFT.Proxies.Application.TokenSecurityService.generateTokenSecurityRequest();
            inValue.TokenSecurityRequest = TokenSecurityRequest;
            return ((Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService)(this)).generateTokenSecurityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdResponse Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService.getTokenSecurityByTokenId(Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest request) {
            return base.Channel.getTokenSecurityByTokenId(request);
        }
        
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationResponseType getTokenSecurityByTokenId(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest) {
            Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest inValue = new Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest();
            inValue.TokenSecurityInformationRequest = TokenSecurityInformationRequest;
            Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdResponse retVal = ((Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService)(this)).getTokenSecurityByTokenId(inValue);
            return retVal.TokenSecurityInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdResponse> Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService.getTokenSecurityByTokenIdAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest request) {
            return base.Channel.getTokenSecurityByTokenIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdResponse> getTokenSecurityByTokenIdAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest) {
            Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest inValue = new Yanbal.SFT.Proxies.Application.TokenSecurityService.getTokenSecurityByTokenIdRequest();
            inValue.TokenSecurityInformationRequest = TokenSecurityInformationRequest;
            return ((Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService)(this)).getTokenSecurityByTokenIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdResponse Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService.setExpireTokenSecurityById(Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest request) {
            return base.Channel.setExpireTokenSecurityById(request);
        }
        
        public Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationResponseType setExpireTokenSecurityById(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest) {
            Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest inValue = new Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest();
            inValue.TokenSecurityInformationRequest = TokenSecurityInformationRequest;
            Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdResponse retVal = ((Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService)(this)).setExpireTokenSecurityById(inValue);
            return retVal.TokenSecurityInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdResponse> Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService.setExpireTokenSecurityByIdAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest request) {
            return base.Channel.setExpireTokenSecurityByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdResponse> setExpireTokenSecurityByIdAsync(Yanbal.SFT.Proxies.Application.TokenSecurityService.TokenSecurityInformationRequestType TokenSecurityInformationRequest) {
            Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest inValue = new Yanbal.SFT.Proxies.Application.TokenSecurityService.setExpireTokenSecurityByIdRequest();
            inValue.TokenSecurityInformationRequest = TokenSecurityInformationRequest;
            return ((Yanbal.SFT.Proxies.Application.TokenSecurityService.ITokenSecurityService)(this)).setExpireTokenSecurityByIdAsync(inValue);
        }
    }
}
