//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Policy.Culture {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Policy.Culture.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelCultureCode {
            get {
                return ResourceManager.GetString("LabelCultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un Código de 4 caracteres..
        /// </summary>
        public static string LabelCultureCodeLength {
            get {
                return ResourceManager.GetString("LabelCultureCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Código de Internacionalización ya se encuentra registrado..
        /// </summary>
        public static string LabelExistingCulture {
            get {
                return ResourceManager.GetString("LabelExistingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Números Decimales.
        /// </summary>
        public static string LabelFormatDecimalNumbers {
            get {
                return ResourceManager.GetString("LabelFormatDecimalNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Números Enteros.
        /// </summary>
        public static string LabelFormatIntegerNumbers {
            get {
                return ResourceManager.GetString("LabelFormatIntegerNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string LabelGridCountry {
            get {
                return ResourceManager.GetString("LabelGridCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelGridCultureCode {
            get {
                return ResourceManager.GetString("LabelGridCultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Números Decimales.
        /// </summary>
        public static string LabelGridFormatDecimalNumbers {
            get {
                return ResourceManager.GetString("LabelGridFormatDecimalNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Números Enteros.
        /// </summary>
        public static string LabelGridFormatIntegerNumbers {
            get {
                return ResourceManager.GetString("LabelGridFormatIntegerNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string LabelGridLanguage {
            get {
                return ResourceManager.GetString("LabelGridLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Fecha Larga.
        /// </summary>
        public static string LabelGridLongDateFormat {
            get {
                return ResourceManager.GetString("LabelGridLongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Hora Larga.
        /// </summary>
        public static string LabelGridLongTimeFormat {
            get {
                return ResourceManager.GetString("LabelGridLongTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Símbolo Negativo.
        /// </summary>
        public static string LabelGridNegativeSymbol {
            get {
                return ResourceManager.GetString("LabelGridNegativeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango para Años con dos Dígitos.
        /// </summary>
        public static string LabelGridRangeForTwoDigitYears {
            get {
                return ResourceManager.GetString("LabelGridRangeForTwoDigitYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Fecha Corta.
        /// </summary>
        public static string LabelGridShortDateFormat {
            get {
                return ResourceManager.GetString("LabelGridShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de Hora Corta.
        /// </summary>
        public static string LabelGridShortTimeFormat {
            get {
                return ResourceManager.GetString("LabelGridShortTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Internacionalización.
        /// </summary>
        public static string LabelInternacionalizationCode {
            get {
                return ResourceManager.GetString("LabelInternacionalizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato Fecha Larga.
        /// </summary>
        public static string LabelLongDateFormat {
            get {
                return ResourceManager.GetString("LabelLongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato Hora Larga.
        /// </summary>
        public static string LabelLongTimeFormat {
            get {
                return ResourceManager.GetString("LabelLongTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Símbolo Negativo.
        /// </summary>
        public static string LabelNegativeSymbol {
            get {
                return ResourceManager.GetString("LabelNegativeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P.
        /// </summary>
        public static string LabelNegativeSymbolParenthesis {
            get {
                return ResourceManager.GetString("LabelNegativeSymbolParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.
        /// </summary>
        public static string LabelNegativeSymbolSign {
            get {
                return ResourceManager.GetString("LabelNegativeSymbolSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango para Años con Dos Dígitos.
        /// </summary>
        public static string LabelRangeForTwoDigitYears {
            get {
                return ResourceManager.GetString("LabelRangeForTwoDigitYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango para Años con Dos Dígitos.
        /// </summary>
        public static string LabelRangeLimitYears {
            get {
                return ResourceManager.GetString("LabelRangeLimitYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato Fecha Corta.
        /// </summary>
        public static string LabelShortDateFormat {
            get {
                return ResourceManager.GetString("LabelShortDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato Hora Corta.
        /// </summary>
        public static string LabelShortTimeFormat {
            get {
                return ResourceManager.GetString("LabelShortTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internacionalización.
        /// </summary>
        public static string LabelTitleCulture {
            get {
                return ResourceManager.GetString("LabelTitleCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Internacionalización.
        /// </summary>
        public static string LabelTitleEdit {
            get {
                return ResourceManager.GetString("LabelTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Internacionalización.
        /// </summary>
        public static string LabelTitleNew {
            get {
                return ResourceManager.GetString("LabelTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite superior.
        /// </summary>
        public static string LabelUpperLimitYear {
            get {
                return ResourceManager.GetString("LabelUpperLimitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rango para año superior debe ser mayor o igual a 1999.
        /// </summary>
        public static string LabelValidateSuperiorYear {
            get {
                return ResourceManager.GetString("LabelValidateSuperiorYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rango para año superior debe ser menor o igual a 2999.
        /// </summary>
        public static string LabelValidateSuperiorYearMax {
            get {
                return ResourceManager.GetString("LabelValidateSuperiorYearMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango para años.
        /// </summary>
        public static string LabelValidateYearRange {
            get {
                return ResourceManager.GetString("LabelValidateYearRange", resourceCulture);
            }
        }
    }
}
