//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yanbal.SFT.Presentation.Web.Source.Resources.Policy.Parameter {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yanbal.SFT.Presentation.Web.Source.Resources.Policy.Parameter.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Agregar.
        /// </summary>
        public static string LabelAllowAddValue {
            get {
                return ResourceManager.GetString("LabelAllowAddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Modificar.
        /// </summary>
        public static string LabelAllowModifyValue {
            get {
                return ResourceManager.GetString("LabelAllowModifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Inicial.
        /// </summary>
        public static string LabelBeginSection {
            get {
                return ResourceManager.GetString("LabelBeginSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Mínimo de 3 Caracteres.
        /// </summary>
        public static string LabelCodeMinLength {
            get {
                return ResourceManager.GetString("LabelCodeMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelCodeSection {
            get {
                return ResourceManager.GetString("LabelCodeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LabelDescriptionSection {
            get {
                return ResourceManager.GetString("LabelDescriptionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Final.
        /// </summary>
        public static string LabelEndSection {
            get {
                return ResourceManager.GetString("LabelEndSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular el Parámetro porque está siendo utilizado en la opción de Fórmulas.
        /// </summary>
        public static string LabelExistingInTableFormula {
            get {
                return ResourceManager.GetString("LabelExistingInTableFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe otro Parámetro con el mismo Código o Nombre.
        /// </summary>
        public static string LabelExistingName {
            get {
                return ResourceManager.GetString("LabelExistingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular el Parámetro porque está siendo utilizado en la opción Orden de Combinación de Parámetros.
        /// </summary>
        public static string LabelExistingParameterInTableCombinationOrder {
            get {
                return ResourceManager.GetString("LabelExistingParameterInTableCombinationOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede anular el Parámetro porque está siendo utilizado en la opción de Orden de Combinación de Parámetros y en la opción de Fórmulas.
        /// </summary>
        public static string LabelExistingParameterInTableCombinationOrderFormula {
            get {
                return ResourceManager.GetString("LabelExistingParameterInTableCombinationOrderFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Agregar.
        /// </summary>
        public static string LabelGridAllowAddValue {
            get {
                return ResourceManager.GetString("LabelGridAllowAddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Modificar.
        /// </summary>
        public static string LabelGridAllowModifyValue {
            get {
                return ResourceManager.GetString("LabelGridAllowModifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelGridCode {
            get {
                return ResourceManager.GetString("LabelGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LabelGridDescription {
            get {
                return ResourceManager.GetString("LabelGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string LabelGridName {
            get {
                return ResourceManager.GetString("LabelGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Parámetro.
        /// </summary>
        public static string LabelGridParameterType {
            get {
                return ResourceManager.GetString("LabelGridParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secciones.
        /// </summary>
        public static string LabelGridSections {
            get {
                return ResourceManager.GetString("LabelGridSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Parámetro.
        /// </summary>
        public static string LabelParameterType {
            get {
                return ResourceManager.GetString("LabelParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negocio.
        /// </summary>
        public static string LabelParametroBusiness {
            get {
                return ResourceManager.GetString("LabelParametroBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string LabelParametroSystem {
            get {
                return ResourceManager.GetString("LabelParametroSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Parámetro.
        /// </summary>
        public static string LabelTitleEdit {
            get {
                return ResourceManager.GetString("LabelTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Parámetro.
        /// </summary>
        public static string LabelTitleNew {
            get {
                return ResourceManager.GetString("LabelTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string LabelTitleParameter {
            get {
                return ResourceManager.GetString("LabelTitleParameter", resourceCulture);
            }
        }
    }
}
